//define fonts as lists of objects
const fonts = {
  semi_bold: {
    familyName: 'SemiBold',
    familySrc: '/font/PlusJakartaSans-semiBold.ttf',
  },
  bold: {
    familyName: 'Bold',
    familySrc: '/font/PlusJakartaSans-Bold.ttf',
  },
  medium:{
    familyName: 'Medium',
    familySrc: '/font/PlusJakartaSans-Medium.ttf',
  },
  light: {
    familyName: 'Light',
    familySrc: '/font/PlusJakartaSans-Light.ttf',
  },
  regular: {
    familyName: 'Regular',
    familySrc: '/font/PlusJakartaSans-Regular.ttf',
  },
  extraBold: {
    familyName: 'ExtraBold',
    familySrc: '/font/PlusJakartaSans-ExtraBold.ttf',
  },
  italic:{
    familyName: 'Italic',
    familySrc: '/font/PlusJakartaSans-Italic.ttf',
  }
};

export default fonts;
